name: flutter_ui
description: Fluter user interfaces
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: any
  package_info: ^2.0.2
  dio: ^5.4.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.5
  sqflite: ^2.3.0
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  internet_connection_checker: ^1.0.0+1
  change_app_package_name: ^1.1.0
  flutx:
  image_picker: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
